[package]
name = "migration"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-schema = { version = "0.5.0", default-features = false, features = [ "migration", "debug-print" ] }
rust-demo-core = { path = "../rust-demo-core" }


